spring.application.name=profit-pulse-backend
# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/profitpulse
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Secret (used in our JwtUtil)
jwt.secret=mysecretkey

# Server Port (optional)
server.port=8081
logging.level.org.springframework.security=DEBUG
